version: '3.9'

services:
  reverse-proxy:
    container_name: traefik
    restart: always
    image: traefik:latest
    networks:
      - web
    environment:
      - TZ=Europe/Paris
    ports:
      - "443:443"
      - "80:80"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Pour que Traefik puisse écouter les événements Docker
      - ./traefik.yaml:/etc/traefik/traefik.yaml   # Fichier traefik avec la configuration static
      - ./custom:/etc/traefik/custom:ro            # Dossier custom avec la configuraiton dynamique
      - ./log:/log                                 # Volume ou seront stocké les logs
      - ./certs:/letsencrypt                       # Volume ou sera stocké le fichier acme.json
    labels:   
# TRAEFIK -> A faire : Déplacer dans traefik/custom/traefik.yaml
      - "traefik.http.routers.api.rule=Host(`traefik.domain.local`)"   # Pour la route 'api' -> Attrape toute les requêtes de 'traefik.domain.fr'
      - "traefik.http.routers.api.service=api@internal"                # Pour la route 'api' -> Utiliser le service 'api' sur provider 'internal' 
      - "traefik.http.routers.api.entrypoints=https,http"              # Pour la route 'api' -> Utiliser l'entrypoint 'https' sinon 'http'
      - "traefik.http.services.api.loadbalancer.server.port=8080"      # Pour le service 'api' -> Indique que le port à exposer est le 8080

networks:
  web:  
