# global:
#  sendAnonymousUsage: false  # Désactivation de l'envoi de donnée
#  checknewversion=false"     # Puisque dockerisé, on désactive le check de mise à jour

accessLog:
  filePath: "/log/access.log" # Répertoire ou sont stocké les logs d'accès
  bufferingSize : 100         # Buffer de 100 lignes
  
api:
  insecure: true   # Activer pour exposer l'api sur 8080
  dashboard: true  # Pour activer le dashboard
  debug: true      # Activer le debug

log:
  level: DEBUG                  # niveau de debug
  filePath: "/log/traefik.log"  # Répertoire ou sont stocké les logs Traefik
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # Le démon Docker écoute sur le socket Unix /var/run/docker.sock
#    exposedbydefault: false                # ??
#    watch: true                            # ??
#    swarmmode: true                        # ??
  file:
    directory: /etc/traefik/custom          # Permets de charger les configurations dans le répertoire (tout les yaml et toml
    watch: true                             # Permets de surveiller le répertoire précédent pour charger dynamiquement les configurations

entryPoints:
  http:                    # Création de l'entrypoint 'http'
    address: ":80"         # Qui écoute le port 80
    http:
      redirections:        # Active la redirection
        entrypoint:
          scheme: "https"
          to: "https"      # Vers l'entrypoint 'https'
  https:                   # Création de l'entrypoint 'https'
    address: ":443"        # Qui écoute le port 443

certificatesResolvers:                   # Permet de définir un challenge http pour la résolution des certificats SSL
  letsencrypt:                           # Nom du resolver (Personnalisable)
    acme:                                # Active ACME (Let's Encrypt): Automatique SSL.
      email: "mail@gmail.com"   # Adresse e-mail utilisée pour l'inscription
      storage: "letsencrypt/acme.json"   # Fichier utilisé pour le stockage des certificats.
      httpChallenge:                     # Utiliser un défi ACME HTTP-01
        entryPoint: "http"               # EntryPoint à utiliser pour les défis HTTP-01
